// generated by unplugin-vue-components
// We suggest you to commit this file into source control
// Read more: https://github.com/vuejs/vue-next/pull/3399
import '@vue/runtime-core'

declare module '@vue/runtime-core' {
  export interface GlobalComponents {
    Block: typeof import('./src/components/Block.vue')['default']
    D40Sidebar: typeof import('./src/sections/D40Sidebar.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    SkipLink: typeof import('./src/components/SkipLink.vue')['default']
    TheFooter: typeof import('./src/sections/TheFooter.vue')['default']
    TheHeader: typeof import('./src/sections/TheHeader.vue')['default']
  }
}

export {}
