const colors = require("tailwindcss/colors");
const clayFonts = 'system-ui,-apple-system,BlinkMacSystemFont,"Segoe UI",Roboto,Oxygen-Sans,Ubuntu,Cantarell,"Helvetica Neue",Arial,sans-serif,"Apple Color Emoji","Segoe UI Emoji","Segoe UI Symbol"';
const clayBreakpoints = {
    xs: "0px",
    sm: "576px",
    md: "768px",
    lg: "992px",
    xl: "1280px",
    "2xl": "1536px",
};

module.exports = {
    prefix: "tw-",
    important: true,
    purge: false,
    dark: false,
    corePlugins: {
        // container: false,
        // boxDecorationBreak: false,
        // boxSizing: false,
        // display: false,
        // float: false,
        // clear: false,
        // isolation: false,
        // objectFit: false,
        // objectPosition: false,
        // overflow: false,
        // overscrollBehavior: false,
        // position: false,
        // inset: false,
        // visibility: false,
        // zIndex: false,
        // flexDirection: false,
        // flexWrap: false,
        // flex: false,
        // flexGrow: false,
        // flexShrink: false,
        // order: false,
        // gridTemplateColumns: false,
        // gridColumn: false,
        // gridColumnStart: false,
        // gridColumnEnd: false,
        // gridTemplateRows: false,
        // gridRow: false,
        // gridRowStart: false,
        // gridRowEnd: false,
        // gridAutoFlow: false,
        // gridAutoColumns: false,
        // gridAutoRows: false,
        // gap: false,
        // justifyContent: false,
        // justifyItems: false,
        // justifySelf: false,
        // alignContent: false,
        // alignItems: false,
        // alignSelf: false,
        // placeContent: false,
        // placeItems: false,
        // placeSelf: false,
        // padding: false,
        // margin: false,
        // space: false,
        // width: false,
        // minWidth: false,
        // maxWidth: false,
        // height: false,
        // minHeight: false,
        // maxHeight: false,
        // fontFamily: false,
        // fontSize: false,
        // fontSmoothing: false,
        // fontStyle: false,
        // fontWeight: false,
        // fontVariantNumeric: false,
        // letterSpacing: false,
        // lineHeight: false,
        // listStyleType: false,
        // listStylePosition: false,
        // placeholderColor: false,
        // placeholderOpacity: false,
        // textAlign: false,
        // textColor: false,
        // textOpacity: false,
        // textDecoration: false,
        // textTransform: false,
        // textOverflow: false,
        // verticalAlign: false,
        // whitespace: false,
        // wordBreak: false,
        // backgroundAttachment: false,
        // backgroundClip: false,
        // backgroundColor: false,
        // backgroundOpacity: false,
        // backgroundPosition: false,
        // backgroundRepeat: false,
        // backgroundSize: false,
        // backgroundImage: false,
        // gradientColorStops: false,
        // borderRadius: false,
        // borderWidth: false,
        // borderColor: false,
        // borderOpacity: false,
        // borderStyle: false,
        // divideWidth: false,
        // divideColor: false,
        // divideOpacity: false,
        // divideStyle: false,
        // ringWidth: false,
        // ringColor: false,
        // ringOpacity: false,
        // ringOffsetWidth: false,
        // ringOffsetColor: false,
        // boxShadow: false,
        // opacity: false,
        // mixBlendMode: false,
        // backgroundBlendMode: false,
        // filter: false,
        // blur: false,
        // brightness: false,
        // contrast: false,
        // dropShadow: false,
        // grayScale: false,
        // hueRotate: false,
        // invert: false,
        // saturate: false,
        // sepia: false,
        // backdropFilter: false,
        // backdropBlur: false,
        // backdropBrightness: false,
        // backdropContrast: false,
        // backdropGrayscale: false,
        // backdropHueRotate: false,
        // backdropInvert: false,
        // backdropOpacity: false,
        // backdropSaturate: false,
        // backdropSepia: false,
        // borderCollapse: false,
        // tableLayout: false,
        // transitionProperty: false,
        // transitionDuration: false,
        // transitionTimingFunction: false,
        // transitionDelay: false,
        // animation: false,
        // transform: false,
        // transformOrigin: false,
        // scale: false,
        // rotate: false,
        // translate: false,
        // skew: false,
        // appearance: false,
        // cursor: false,
        // outline: false,
        // pointerEvents: false,
        // resize: false,
        // userSelect: false,
        // fill: false,
        // stroke: false,
        // strokeWidth: false,
        // accessibility: false,
    },
    theme: {
        // Extend
        fontFamily: {
            text: `Barlow,${clayFonts}`,
            heading: `Montserrat,${clayFonts}`,
        },
        colors: {
            transparent: "transparent",
            current: "currentColor",
            black: colors.black,
            white: colors.white,
            gray: colors.coolGray,
        },
        borderRadius: {
            none: "0",
            sm: "0.125rem",
            DEFAULT: "0.25rem",
            md: "0.375rem",
            lg: "0.5rem",
            xl: "1rem",
            "2xl": "1.5rem",
            full: "9999px",
        },
        zIndex: {
            0: 0,
            5: 5,
            10: 10,
            20: 20,
            30: 30,
            40: 40,
            50: 50,
            60: 60,
            70: 70,
            80: 80,
            90: 90,
            100: 100,
        },
        screens: clayBreakpoints,
    },
};
